 CREATE DATABASE CUSTOMER_TWO;
USE CUSTOMER_TWO;

CREATE TABLE CUSTOMER_TWO (
    CustomerID INT PRIMARY KEY ,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100)
);

CREATE TABLE CUSTOMER_PHONE(
    PhoneID INT PRIMARY KEY ,
    CustomerID INT,
    PhoneNumber VARCHAR(15),
    PhoneType VARCHAR(10),
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER_TWO(CustomerID)

);