DROP DATABASE IF EXISTS DEPARTMENT_3NF;
CREATE DATABASE DEPARTMENT_3NF;
USE DEPARTMENT_3NF;

CREATE DATABASE IF NOT EXISTS DEPARTMENT_3NF;
USE DEPARTMENT_3NF;

-- ✅ 3NF (ট্রানজিটিভ নির্ভরতা দূর করা)
CREATE TABLE DEPARTMENT_3NF(
    DeptID INT PRIMARY KEY ,
     DeptName VARCHAR(50) NOT NULL,
    DeptLocation VARCHAR(50),
    ManagerName VARCHAR(100)
);

CREATE TABLE EMPLOYEE
(
    EmpID    INT PRIMARY KEY,
    EmpName  VARCHAR(100) NOT NULL,
    DeptID   INT,
    HireDate DATE,
    Salary   DECIMAL(10, 2),
    FOREIGN KEY (DeptID) REFERENCES DEPARTMENT_3NF(DeptID)
);

INSERT INTO DEPARTMENT_3NF VALUES
(10, 'IT', 'Dhaka', 'Mr. Rahman'),
(20, 'HR', 'Chittagong', 'Mrs. Begum');

INSERT INTO EMPLOYEE VALUES
(1, 'Lisa Mazzone', 10, '2024-01-15', 50000.00),
(2, 'John Smith', 20, '2024-02-01', 45000.00);