
DROP DATABASE IF EXISTS ORDERS_2NF;
CREATE DATABASE ORDERS_2NF;
USE ORDERS_2NF;

CREATE DATABASE IF NOT EXISTS ORDERS_2NF;
USE ORDERS_2NF;
-- ✅ 2NF (আংশিক নির্ভরতা দূর করা)


CREATE TABLE ORDERS(
    OrderID INT PRIMARY KEY

);

CREATE TABLE PRODUCT(
    ProductID INT PRIMARY KEY ,
    ProductName VARCHAR(100) NOT NULL,
    Category VARCHAR(50),
    UnitPrice DECIMAL(10,2)
);

CREATE TABLE ORDER_ITEM
(
    OrderID   INT,
    ProductID INT,
    Quantity  INT NOT NULL,
    PRIMARY KEY (OrderID, ProductID),
    FOREIGN KEY (ProductID) REFERENCES PRODUCT (ProductID),
    FOREIGN KEY (OrderID) REFERENCES ORDERS (OrderID)
);


INSERT INTO ORDERS VALUES(1001);

INSERT INTO PRODUCT VALUES
(101, 'Laptop', 'Electronics', 55000.00),
(102, 'Mouse', 'Electronics', 500.00);

INSERT INTO ORDER_ITEM VALUES
(1001, 101, 1),
(1001, 102, 2);