DROP DATABASE IF EXISTS NORMALIZATION_DB;
CREATE DATABASE NORMALIZATION_DB;
USE NORMALIZATION_DB;

CREATE DATABASE IF NOT EXISTS NORMALIZATION_DB;
USE NORMALIZATION_DB;


-- ✅ 1NF (প্রতি ঘরে একটিমাত্র মান)

CREATE TABLE STUDENT_1NFA (
    StudentID INT PRIMARY KEY ,
    StudentName VARCHAR(100),
    PhoneNumbers VARCHAR(200) UNIQUE
);

CREATE TABLE STUDENT_PHONE (
    PhoneID INT PRIMARY KEY AUTO_INCREMENT,
    StudentID INT NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    PhoneType VARCHAR(10),
    FOREIGN KEY (StudentID) REFERENCES STUDENT_1NFA(StudentID)
);

INSERT INTO STUDENT_1NFA VALUES (1, 'Lisa Mazzone', 'lisa@email.com');
INSERT INTO STUDENT_PHONE VALUES
(1, 1, '12345', 'Home'),
(2, 1, '67890', 'Mobile');
