DROP DATABASE IF EXISTS NORMALIZATION_DB;
CREATE DATABASE NORMALIZATION_DB;
USE NORMALIZATION_DB;

CREATE DATABASE IF NOT EXISTS NORMALIZATION_DB;
USE NORMALIZATION_DB;


    CREATE TABLE STUDENT_SPORT_4NF(
    StudentID INT,
    Sport VARCHAR(50),
        PRIMARY KEY (StudentID, Sport),
        FOREIGN KEY(StudentID) REFERENCES STUDENT_SPORT_4NF(StudentID)
    );

CREATE TABLE STUDENT_HOBBY(
    StudentID INT,
    Hobby VARCHAR(50),
    PRIMARY KEY (StudentID, Hobby),
    FOREIGN KEY (StudentID) REFERENCES  STUDENT_SPORT_4NF(StudentID)

)