DROP DATABASE IF EXISTS  NORMALIZATION_DB;
CREATE DATABASE  NORMALIZATION_DB;
USE  NORMALIZATION_DB;

CREATE DATABASE IF NOT EXISTS  NORMALIZATION_DB;
USE  NORMALIZATION_DB;

-- STUDENT (must exist first)
CREATE TABLE STUDENT_1NFA (
    StudentID INT PRIMARY KEY,
    StudentName VARCHAR(100)
);

create table TEACHER
(
    TeacherID int PRIMARY KEY
);
CREATE TABLE SUBJECT_TEACHER_BCNF(

    SubjectID INT PRIMARY KEY,
    SubjectName VARCHAR(100),
    TeacherID INT,
    FOREIGN KEY (TeacherID) REFERENCES TEACHER(TeacherID)
);

CREATE TABLE ENROLMENT(
    StudentID INT,
    SubjectID INT,
    Enrollment DATE,
    Grade CHAR(2),
    PRIMARY KEY (StudentID, SubjectID),
    FOREIGN KEY (SubjectID) REFERENCES SUBJECT_TEACHER_BCNF(SubjectID),
   FOREIGN KEY (StudentID) REFERENCES STUDENT_1NFA(StudentID)
);